### ISSUE TITLE
This project needs a maintainer

### ISSUE THREAD

**Issue by bashu** [HubSpot/sanetime#16]
Hi,

This repository seems to lack maintenance, I propose myself as a new maintainer.

Could you give me the right to push in your repository or just transfer it on my account in github?

Thank you!

PS: I really need an official python3 "ready" release

**Comment by bashu** [comment]
@prior halp

**Comment by prior** [comment]
@bashu still interested in being maintainer?

**Comment by bashu** [comment]
@prior yes, still interested

**Comment by prior** [comment]
you've got full admin rights -- enjoy, and thank you!

**Comment by bashu** [comment]
@prior suddenly I lost access

**Comment by kmclarnon** [comment]
Hi @bashu, I believe this was the result of some security changes that we made.  I'll see what I can do to fix it
