### ISSUE TITLE
Test failure

### ISSUE THREAD

**Issue by msabramo** [HubSpot/sanetime#5]
Still occurring (I think you closed my prior issue #4 because you thought that my pull request #3 fixed it but it did not -- PR #3 was just to make `python setup.py` run the test -- not to fix the test failure):

When I do `python setup.py test` with Python 2.7 on OS X 10.6.8, I get:

```
======================================================================
FAIL: test_timezone_construction (sanetime.test.test_time.SaneTimeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/marca/dev/git-repos/sanetime/sanetime/test/test_time.py", line 72, in test_timezone_construction
    self.assertEquals((NY_JUL_MICROS,TZ_UTC), time('2012-06-01 00:00:00 EDT')._tuple)
AssertionError: Tuples differ: (1338523200000000, <UTC>) != (1338508800000000, <UTC>)

First differing element 0:
1338523200000000
1338508800000000

- (1338523200000000, <UTC>)
?       ^^^

+ (1338508800000000, <UTC>)
?       ^^^


----------------------------------------------------------------------
Ran 30 tests in 0.022s

FAILED (failures=1)
```

I am in the U.S. Pacific timezone.

**Comment by msabramo** [comment]
So I did the arithmetic on the two numbers above and they are exactly 4 hours (in microseconds) apart. Even more interesting, if I set my timezone to U.S. Eastern, then the tests pass! Hmmm....

**Comment by prior** [comment]
figured this out-- it failed cuz of another bit of strangeness coming from dateutils.parser.  With some timezone decorations it decides to attach a timezone only if you happen to be in that timezone (totally bizarre)

if your machine is in EDT you get this

``` python
>>> from dateutil import parser
>>> parser.parse('7/1/00 00:00 EDT')
datetime.datetime(2000, 7, 1, 0, 0, tzinfo=tzlocal())
>>> parser.parse('7/1/00 00:00 PDT')
datetime.datetime(2000, 7, 1, 0, 0)
```

you'll get the opposite if your running in PDT.  

fix incoming...

**Comment by prior** [comment]
should be all good now-- everything passes for me in several different timezones now
https://github.com/HubSpot/sanetime/commit/75caf9a7e1aeecbb065787cbf3babc1c008603f9
